[package]
name = "scop"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
vulkano = "0.35.1"
vulkano-shaders = "0.35.0"
winit = { version = "0.30.9", default-features = true, features = ["rwh_05"]}
